id: P004524
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:29:39.841466
source_metadata:
  id: bdr:W1CZ2260
  title: ཕྱག་མཚན་དང་མཆོད་རྫས་ཡོ་བྱད་ཀྱི་རྣམ་བཞག
  author: ''
  volumes:
    d26922313c1e43999ef55ae15b946600:
      image_group_id: I1CZ2299
      title: ''
      volume_number: 1
      total_pages: 138
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
