id: IFAC14CD7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:59:50+00:00'
last_modified: '2022-06-08T01:41:27.491844+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2260
  title: ཕྱག་མཚན་དང་མཆོད་རྫས་ཡོ་བྱད་ཀྱི་རྣམ་བཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC5E:
      image_group_id: I1CZ2299
      title: ''
      total_pages: 138
      order: 1
      base_file: CC5E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
